### ISSUE TITLE
Kded5 crashes after enabling laptop monitor

### ISSUE THREAD

**Issue by romangg** [winft/disman#9]
In GitLab by @magiblot on Jun 19, 2020, 10:59

When I do the following:

1. Connect my laptop to an external monitor.
2. Start Plasma Wayland session with `QT_QPA_PLATFORM=xcb`
3. Disable the laptop screen.
4. Enable the laptop screen.

Kded5 crashes (plasmashell or other applications do not):

```
#0  0x00007faa8e0d0355 in raise () at /usr/lib/libc.so.6
#1  0x00007faa8f1d80e6 in KCrash::defaultCrashHandler(int) () at /usr/lib/libKF5Crash.so.5
#2  0x00007faa8e0d03e0 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007faa8019c60f in XRandR::getXProperty(unsigned int, unsigned int, unsigned long&) (output=output@entry=33, atom=atom@entry=399, len=@0x7ffed3c2ac98: 0) at /usr/src/debug/disman/backends/xrandr/xrandr.cpp:241
#4  0x00007faa8019c703 in XRandR::outputEdid(unsigned int) (outputId=33) at /usr/src/debug/disman/backends/xrandr/xrandr.cpp:261
#5  0x00007faa801aaecf in XRandROutput::edid() const (this=0x5643be830a30) at /usr/src/debug/disman/backends/xrandr/xrandroutput.cpp:121
#6  0x00007faa8019c579 in XRandR::edid(int) const (this=this@entry=0x5643be831580, outputId=<optimized out>) at /usr/src/debug/disman/backends/xrandr/xrandr.cpp:226
#7  0x00007faa80cdce29 in Disman::GetConfigOperationPrivate::loadEdid(Disman::AbstractBackend*) (backend=0x5643be831580, this=<optimized out>) at /usr/src/debug/disman/src/getconfigoperation.cpp:196
#8  Disman::GetConfigOperationPrivate::loadEdid(Disman::AbstractBackend*) (this=<optimized out>, backend=0x5643be831580) at /usr/src/debug/disman/src/getconfigoperation.cpp:185
#9  0x00007faa80cdcf56 in Disman::GetConfigOperation::start() (this=0x5643bea24130) at /usr/src/debug/disman/src/getconfigoperation.cpp:178
#10 0x00007faa8e7170b2 in QObject::event(QEvent*) (this=0x5643bea24130, e=0x5643be832c20) at kernel/qobject.cpp:1314
#11 0x00007faa8f3de702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x5643bea24130, e=0x5643be832c20) at kernel/qapplication.cpp:3671
#12 0x00007faa8e6ea69a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5643bea24130, event=0x5643be832c20) at ../../include/QtCore/5.15.0/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:325
#13 0x00007faa8e6ed183 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x5643be6c3bb0) at kernel/qcoreapplication.cpp:1815
#14 0x00007faa8e743bd4 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x5643be737460) at kernel/qeventdispatcher_glib.cpp:277
#15 0x00007faa8d2de43c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007faa8d32bfa9 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007faa8d2dd221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007faa8e743211 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5643be749ef0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#19 0x00007faa8e6e901c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffed3c2b1c0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:141
#20 0x00007faa8e6f14a4 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#21 0x00005643be68e6f5 in  ()
#22 0x00007faa8e0bb002 in __libc_start_main () at /usr/lib/libc.so.6
#23 0x00005643be68e8ce in  ()
```

The crash due to `xcb_randr_get_output_property_reply` returning `nullptr`:

```
quint8* XRandR::getXProperty(xcb_randr_output_t output, xcb_atom_t atom, size_t &len)
{
    quint8 *result;

    auto cookie = xcb_randr_get_output_property(XCB::connection(), output, atom,
                                                XCB_ATOM_ANY,
                                                0, 100, false, false);
    auto reply = xcb_randr_get_output_property_reply(XCB::connection(), cookie, nullptr);

    if (reply->type == XCB_ATOM_INTEGER && reply->format == 8) {
        result = new quint8[reply->num_items];
        memcpy(result, xcb_randr_get_output_property_data(reply), reply->num_items);
        len = reply->num_items;
    } else {
        result = nullptr;
    }

    free(reply);
    return result;
}
```
gdb says `cookie` is `$5 = {sequence = 111}`.

I was using mainline Kwin this time.

<details>
<summary>Software versions:</summary>

```
linux 5.7.3
mesa 20.1.1
Qt 5.15.0
kwin 5.19.1
kwayland-server 5.19.1
kwayland 5.71.0
disman 0.519.0.r0.g9edf413
kdisplay 5.19.0.beta.0.r2.ga0504e4
libwayland 1.18.0
wayland-egl 18.1.0
xwayland 1.20.8
libxkbcommon 0.10.0
libinput 1.15.5
libdrm 2.4.102
libxcb 1.14
libx11 1.6.9
```
</details>

**Comment by romangg** [comment]
Could be fixed with the large redesign. Can you confirm?

**Comment by romangg** [comment]
In GitLab by @magiblot on Aug 22, 2020, 17:30

I upgraded to latest disman, kdisplay and wrapland after reproducing this again earlier today and I no longer see any crashes. However, I am using mainline Kwin and plasmashell has trouble showing up after the upgrade ([link to video](https://drive.google.com/file/d/1g1mBYxSOVLDsRPy3XM02y-MPC6mEROhs/view?usp=sharing)), but it works fine with mainline kscreen/libkscreen. Should I open a bug? (If so, in what component?)

**Comment by romangg** [comment]
Sorry, I overlooked the question you asked. Hmm, I'm not sure how this would relate to Disman+KDisplay. Normally the KWin <-> plasmashell communication is independent of that.

But you can create a separate issue for that. Thank you. I will try to reproduce then.

I will close the issue here now as the crash seems to be fixed.
